// <auto-generated />
using System;
using CashRegister.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CashRegister.Data.Migrations
{
    [DbContext(typeof(CashRegisterContext))]
    [Migration("20190713183751_SeedingChanges")]
    partial class SeedingChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CashierRegisterCashierId");

                    b.Property<int?>("CashierRegisterRegisterId");

                    b.Property<double>("CustomTaxAmount");

                    b.Property<double>("ExciseDutyAmount");

                    b.Property<Guid>("Guid");

                    b.Property<DateTime>("IssueDate");

                    b.Property<double>("TotalPriceWithTax");

                    b.Property<double>("TotalPriceWithoutTax");

                    b.Property<double>("ValueAddedTaxAmount");

                    b.HasKey("Id");

                    b.HasIndex("CashierRegisterCashierId", "CashierRegisterRegisterId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("cd3eb614-58d5-49f0-906d-e8a5d04f0b47"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 2,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("a17f9c05-4372-4d96-a1dd-9f7f9f20d775"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 3,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("8352c1c1-4b85-4577-955f-0853763156f3"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 4,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("45fe1dc9-4a01-4c29-8108-ef29ac369a8d"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 5,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("8ff69436-7ac2-4d06-957c-ea16d9451ab6"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 6,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("21594c38-6ad9-4dd0-b771-e2ae4ef763a1"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 7,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("1274a118-c3e1-466b-b46c-ced9c8afe9e7"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 8,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("6eb9f90c-9d05-4211-93b8-804fa98daaff"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 9,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("64e7967f-cc9f-43a5-92fc-db298a394418"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 10,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("e102b21e-c487-43f7-96dd-5acfd50aab65"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 11,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("a127a536-baee-4e7e-9475-5cf105865dad"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 12,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("344ead6f-987f-4593-b16c-86d431901949"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 13,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("43dea670-6f79-4d60-92cb-1cac5b6dc187"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 14,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("23ce327b-1d51-4c26-a43d-47c73fed22d9"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 15,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("5cb19464-276b-4f23-866a-1462a91efc2e"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 16,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("e5d73c4d-9dee-48b6-971c-575def57848b"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 17,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("6dac448e-fcdd-4c61-b580-93ffce44e7dd"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 18,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("ee1c72db-9463-40e8-90b3-d62240e95d62"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 19,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("fecafac4-069c-4653-94fa-a9192ca112bf"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 20,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("f9b1e571-fb08-4f00-bc9e-16bb19a41f6d"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 21,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("e2951169-9af5-450e-ba56-f9bdcc42eb6f"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 22,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("7cf6a7df-7993-424f-a572-533d986a1253"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 23,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("290d679d-9d1c-4c48-972a-b0c607e140ef"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 24,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("f5b6935a-3543-4118-a435-a68e2f532a20"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 25,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("3f19ea71-9639-4d4f-92b1-d20c021f7b2b"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 26,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("d24d3493-786e-4b38-b2ab-54a68534e562"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 27,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("81b56cb4-dbc5-45ce-82fe-af7fb1e8c266"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 28,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("55017bdc-ce59-4ca5-8763-3686798a53c1"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 29,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("4ba3ec02-1665-41f5-ad96-35e5f5ee9418"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 30,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("41413d5b-9e9b-4c61-82b1-c8cfdc382ffd"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 31,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("34ce2fee-2872-460b-82c0-fdbe8037f06b"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 32,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("0337eb01-9871-4307-9d19-1309df6ff8d4"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 33,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("6e25c4a6-f653-4167-9e19-74198e1067eb"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 34,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("8afdb858-16a1-4c61-a440-280ce9c3e317"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 35,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("d8928a63-7974-41a8-8883-716591a9023d"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 36,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("9eb259c2-b174-4ff8-a16b-be3f5fa8a8c7"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 37,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("28d23777-9ab0-49ab-b5e9-6934051a3f42"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 38,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("3bcdcfad-ee78-4a9c-a92c-4436af84b5de"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 39,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("1c8666e7-6866-45b0-9a64-f5db22190dfd"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 40,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("05527817-4427-4d61-aaad-2a77255dfc62"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 41,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("3b432750-ad70-4919-b8ce-f7ca9439f4a5"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 42,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("c82ca035-7806-4efe-b4ad-d42475c9d35b"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 43,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("be8eb4c0-e13c-4e0b-bacf-db41bedf05ef"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 44,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("6bf8a603-84a1-4b75-aa9e-ab781f737a95"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 45,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("b381326b-1cd8-447e-a23d-4bfef69c7f39"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 46,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("9ab84eff-43b3-4bc2-ac23-3418e4c67360"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 47,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("97531cef-d4ec-42db-b8f1-d14ad154323e"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 48,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("456951a5-79b9-4c4c-8164-ba9f0581b3ab"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 49,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("8c0a9b4f-60f0-4cc5-b3aa-c43fab93e9f0"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        });
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.BillProduct", b =>
                {
                    b.Property<int>("BillId");

                    b.Property<int>("ProductId");

                    b.Property<int>("AmountBought");

                    b.Property<double>("PriceAtPurchase");

                    b.Property<int>("TaxAtPurchase");

                    b.HasKey("BillId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("BillProducts");

                    b.HasData(
                        new
                        {
                            BillId = 1,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 2,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 3,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 4,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 5,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 6,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 7,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 8,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 9,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 10,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 11,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 12,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 13,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 14,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 15,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 16,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 17,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 18,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 19,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 20,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 21,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 22,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 23,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 24,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 25,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 26,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 27,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 28,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 29,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 30,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 31,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 32,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 33,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 34,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 35,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 36,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 37,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 38,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 39,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 40,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 41,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 42,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 43,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 44,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 45,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 46,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 47,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 48,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 49,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        });
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Cashier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cashiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mate Matic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jure Juric"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stipe Stipic"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tomo Tomic"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ana Anic"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mila Milic"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Iva Ivic"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Teta Tetic"
                        });
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.CashierRegister", b =>
                {
                    b.Property<int>("CashierId");

                    b.Property<int>("RegisterId");

                    b.HasKey("CashierId", "RegisterId");

                    b.HasIndex("RegisterId");

                    b.ToTable("CashierRegisters");

                    b.HasData(
                        new
                        {
                            CashierId = 1,
                            RegisterId = 1
                        });
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<string>("Barcode");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("Tax");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100,
                            Barcode = "1111111111111",
                            Name = "Banana",
                            Price = 3.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100,
                            Barcode = "1111111111112",
                            Name = "Orange",
                            Price = 4.0,
                            Tax = 5
                        },
                        new
                        {
                            Id = 3,
                            Amount = 100,
                            Barcode = "1111111111113",
                            Name = "Lemon",
                            Price = 3.0,
                            Tax = 20
                        },
                        new
                        {
                            Id = 4,
                            Amount = 100,
                            Barcode = "1111111111114",
                            Name = "Apple",
                            Price = 2.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100,
                            Barcode = "1111111111115",
                            Name = "Cherry",
                            Price = 5.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 6,
                            Amount = 100,
                            Barcode = "1111111111116",
                            Name = "Chewing gum",
                            Price = 7.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 7,
                            Amount = 100,
                            Barcode = "1111111111117",
                            Name = "Apple juice",
                            Price = 12.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 8,
                            Amount = 100,
                            Barcode = "1111111111118",
                            Name = "Apple cider",
                            Price = 15.0,
                            Tax = 5
                        },
                        new
                        {
                            Id = 9,
                            Amount = 100,
                            Barcode = "1111111111119",
                            Name = "Apple pie",
                            Price = 27.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 10,
                            Amount = 100,
                            Barcode = "1111111111120",
                            Name = "Watermelon",
                            Price = 21.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 11,
                            Amount = 100,
                            Barcode = "1111111111121",
                            Name = "Sprite",
                            Price = 10.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 12,
                            Amount = 100,
                            Barcode = "1111111111122",
                            Name = "Fanta",
                            Price = 10.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 13,
                            Amount = 100,
                            Barcode = "1111111111123",
                            Name = "Coca Cola",
                            Price = 10.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 14,
                            Amount = 100,
                            Barcode = "1111111111124",
                            Name = "Orangina",
                            Price = 15.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 15,
                            Amount = 100,
                            Barcode = "1111111111125",
                            Name = "Pepsi",
                            Price = 10.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 16,
                            Amount = 100,
                            Barcode = "1111111111126",
                            Name = "Wine",
                            Price = 137.0,
                            Tax = 5
                        },
                        new
                        {
                            Id = 17,
                            Amount = 100,
                            Barcode = "1111111111127",
                            Name = "Chips",
                            Price = 15.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 18,
                            Amount = 100,
                            Barcode = "1111111111128",
                            Name = "Cigarettes",
                            Price = 24.0,
                            Tax = 5
                        },
                        new
                        {
                            Id = 19,
                            Amount = 100,
                            Barcode = "1111111111129",
                            Name = "Coffe",
                            Price = 34.0,
                            Tax = 20
                        },
                        new
                        {
                            Id = 20,
                            Amount = 100,
                            Barcode = "1111111111130",
                            Name = "Batteries",
                            Price = 42.0,
                            Tax = 5
                        });
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Registers");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 8
                        });
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Bill", b =>
                {
                    b.HasOne("CashRegister.Data.Entities.Models.CashierRegister", "CashierRegister")
                        .WithMany("Bills")
                        .HasForeignKey("CashierRegisterCashierId", "CashierRegisterRegisterId");
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.BillProduct", b =>
                {
                    b.HasOne("CashRegister.Data.Entities.Models.Bill", "Bill")
                        .WithMany("BillProducts")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CashRegister.Data.Entities.Models.Product", "Product")
                        .WithMany("BillProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.CashierRegister", b =>
                {
                    b.HasOne("CashRegister.Data.Entities.Models.Cashier", "Cashier")
                        .WithMany("CashierRegisters")
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CashRegister.Data.Entities.Models.Register", "Register")
                        .WithMany("CashierRegisters")
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
