// <auto-generated />
using System;
using CashRegister.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CashRegister.Data.Migrations
{
    [DbContext(typeof(CashRegisterContext))]
    [Migration("20190713183611_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CashierRegisterCashierId");

                    b.Property<int?>("CashierRegisterRegisterId");

                    b.Property<double>("CustomTaxAmount");

                    b.Property<double>("ExciseDutyAmount");

                    b.Property<Guid>("Guid");

                    b.Property<DateTime>("IssueDate");

                    b.Property<double>("TotalPriceWithTax");

                    b.Property<double>("TotalPriceWithoutTax");

                    b.Property<double>("ValueAddedTaxAmount");

                    b.HasKey("Id");

                    b.HasIndex("CashierRegisterCashierId", "CashierRegisterRegisterId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("b9fe028f-0a8a-4dfd-9bc7-bb9b01d6e47b"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 2,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("96b3568e-0177-4d75-8f1c-9087ca9b9cd6"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 3,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("e5cfa92b-d278-40e1-8400-d54063472f3c"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 4,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("226c03da-6c99-4018-b3ed-67e10aeb0a6c"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 5,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("9e30c971-7de0-4ee5-9af5-eb5b4fe44b85"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 6,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("2f14393d-e2b3-47b6-9674-d2dac7c19cbe"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 7,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("dfdb8e4d-d232-4f6e-b078-0820f69c1816"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 8,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("2cf63692-03a2-4fc1-8b8c-fa021cf96176"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 9,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("e004dbd3-ddc6-4d2a-8428-c7acb364916d"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 10,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("6f490d07-12fd-4e47-8b28-3951be06ec2b"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 11,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("bc356974-6199-4811-b507-c1d3e4ddbc46"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 12,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("2ff6ddbe-eff6-4165-81e0-e4e07938139a"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 13,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("c2b831be-d1b7-4335-a9fc-2694ac282cf9"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 14,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("cec9e087-c372-423f-9201-728415ad94f2"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 15,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("80b08f98-a67f-4f8a-8499-322f270f99d5"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 16,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("a0c645f1-93ab-4bdd-a435-72c2e7f2e857"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 17,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("68719cda-cd0b-4ef0-94e0-3f847c7a2fcd"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 18,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("aa9420b1-5134-4dcd-9d81-4f282be9d26d"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 19,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("7529ab49-5a33-400d-9449-873f0e2e3261"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 20,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("52d3cfd0-e18b-4a7a-8434-1129ecb034bc"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 21,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("0cd8bba0-98c7-4874-9b80-4578ac4fcecd"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 22,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("f64ff6d0-4cc7-46df-8d4c-3e964e115833"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 23,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("5d09c71c-8bc8-4aeb-a32b-3196da9bddbe"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 24,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("0a94ea27-0569-42e2-be8d-31b7380d6a31"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 25,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("08470d06-31f6-4e15-90df-a46e7ee1e550"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 26,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("d4e1cc8f-e4f2-4433-a276-c7fc28b4b8b7"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 27,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("49b239f3-b53a-4b17-b9ef-dd91e5dbd67e"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 28,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("83d8da67-17e2-4c78-a5da-eb4ba6837e8d"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 29,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("fb82b33a-0b21-4d45-a084-5518cc9b35ba"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 30,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("b32626cc-190b-4abc-b5ba-020fee380298"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 31,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("1011cbc1-0599-4da6-9ca3-961440752154"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 32,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("e557e42f-03a8-4b52-9d73-73b0846edd6a"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 33,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("4a693771-a06e-4f64-9e51-8eb250c41a33"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 34,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("7b1abb10-4d5a-4fd9-b64a-76f878cb7930"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 35,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("40e3b300-19b3-4716-8ab6-e76cc450e6b6"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 36,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("09c9abef-2227-497f-a2cd-98768f75edde"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 37,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("facbaded-87c3-491d-bed6-70cde8506acf"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 38,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("623799bc-45a9-46b0-bda0-547857dfd261"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 39,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("cb54ba42-2606-428c-8e81-987a9afa2c34"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 40,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("8ad0cd02-9b10-402b-bcca-d5b07cfeccef"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 41,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("c816b4ac-5390-4e2c-8ed9-30cb2b9c5853"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 42,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("9b3bb25c-a7e1-4c71-b637-dcf065b4247c"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 43,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("d3a30e31-526a-4d1c-b0ec-67d1e5a63ea7"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 44,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("cadcdb0f-e7ca-4136-99da-04e99c22cc12"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 45,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("beb35f10-1b3d-460e-bc4b-a7581868eba7"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 46,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("f30314f2-e89a-470f-8d4c-9e020a94611c"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 47,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("fe6d7e9a-652c-4c1d-81aa-8360fb0b6566"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 48,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("bab2e215-0c35-4f50-bc1b-325e1d831a12"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        },
                        new
                        {
                            Id = 49,
                            CustomTaxAmount = 1.0,
                            ExciseDutyAmount = 1.0,
                            Guid = new Guid("843d2ef9-629e-486c-929a-24940907ccd0"),
                            IssueDate = new DateTime(2012, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPriceWithTax = 1.0,
                            TotalPriceWithoutTax = 20.0,
                            ValueAddedTaxAmount = 1.0
                        });
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.BillProduct", b =>
                {
                    b.Property<int>("BillId");

                    b.Property<int>("ProductId");

                    b.Property<int>("AmountBought");

                    b.Property<double>("PriceAtPurchase");

                    b.Property<int>("TaxAtPurchase");

                    b.HasKey("BillId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("BillProducts");

                    b.HasData(
                        new
                        {
                            BillId = 1,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 2,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 3,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 4,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 5,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 6,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 7,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 8,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 9,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 10,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 11,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 12,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 13,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 14,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 15,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 16,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 17,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 18,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 19,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 20,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 21,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 22,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 23,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 24,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 25,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 26,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 27,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 28,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 29,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 30,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 31,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 32,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 33,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 34,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 35,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 36,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 37,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 38,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 39,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 40,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 41,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 42,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 43,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 44,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 45,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 46,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 47,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 48,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        },
                        new
                        {
                            BillId = 49,
                            ProductId = 1,
                            AmountBought = 1,
                            PriceAtPurchase = 1.0,
                            TaxAtPurchase = 1
                        });
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Cashier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cashiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mate Matic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jure Juric"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stipe Stipic"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tomo Tomic"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ana Anic"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mila Milic"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Iva Ivic"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Teta Tetic"
                        });
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.CashierRegister", b =>
                {
                    b.Property<int>("CashierId");

                    b.Property<int>("RegisterId");

                    b.HasKey("CashierId", "RegisterId");

                    b.HasIndex("RegisterId");

                    b.ToTable("CashierRegisters");

                    b.HasData(
                        new
                        {
                            CashierId = 1,
                            RegisterId = 1
                        });
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<string>("Barcode");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("Tax");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100,
                            Barcode = "1111111111111",
                            Name = "Banana",
                            Price = 3.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100,
                            Barcode = "1111111111112",
                            Name = "Orange",
                            Price = 4.0,
                            Tax = 5
                        },
                        new
                        {
                            Id = 3,
                            Amount = 100,
                            Barcode = "1111111111113",
                            Name = "Lemon",
                            Price = 3.0,
                            Tax = 20
                        },
                        new
                        {
                            Id = 4,
                            Amount = 100,
                            Barcode = "1111111111114",
                            Name = "Apple",
                            Price = 2.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100,
                            Barcode = "1111111111115",
                            Name = "Cherry",
                            Price = 5.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 6,
                            Amount = 100,
                            Barcode = "1111111111116",
                            Name = "Chewing gum",
                            Price = 7.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 7,
                            Amount = 100,
                            Barcode = "1111111111117",
                            Name = "Apple juice",
                            Price = 12.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 8,
                            Amount = 100,
                            Barcode = "1111111111118",
                            Name = "Apple cider",
                            Price = 15.0,
                            Tax = 5
                        },
                        new
                        {
                            Id = 9,
                            Amount = 100,
                            Barcode = "1111111111119",
                            Name = "Apple pie",
                            Price = 27.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 10,
                            Amount = 100,
                            Barcode = "1111111111120",
                            Name = "Watermelon",
                            Price = 21.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 11,
                            Amount = 100,
                            Barcode = "1111111111121",
                            Name = "Sprite",
                            Price = 10.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 12,
                            Amount = 100,
                            Barcode = "1111111111122",
                            Name = "Fanta",
                            Price = 10.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 13,
                            Amount = 100,
                            Barcode = "1111111111123",
                            Name = "Coca Cola",
                            Price = 10.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 14,
                            Amount = 100,
                            Barcode = "1111111111124",
                            Name = "Orangina",
                            Price = 15.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 15,
                            Amount = 100,
                            Barcode = "1111111111125",
                            Name = "Pepsi",
                            Price = 10.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 16,
                            Amount = 100,
                            Barcode = "1111111111126",
                            Name = "Wine",
                            Price = 137.0,
                            Tax = 5
                        },
                        new
                        {
                            Id = 17,
                            Amount = 100,
                            Barcode = "1111111111127",
                            Name = "Chips",
                            Price = 15.0,
                            Tax = 25
                        },
                        new
                        {
                            Id = 18,
                            Amount = 100,
                            Barcode = "1111111111128",
                            Name = "Cigarettes",
                            Price = 24.0,
                            Tax = 5
                        },
                        new
                        {
                            Id = 19,
                            Amount = 100,
                            Barcode = "1111111111129",
                            Name = "Coffe",
                            Price = 34.0,
                            Tax = 20
                        },
                        new
                        {
                            Id = 20,
                            Amount = 100,
                            Barcode = "1111111111130",
                            Name = "Batteries",
                            Price = 42.0,
                            Tax = 5
                        });
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Registers");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 8
                        });
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Bill", b =>
                {
                    b.HasOne("CashRegister.Data.Entities.Models.CashierRegister", "CashierRegister")
                        .WithMany("Bills")
                        .HasForeignKey("CashierRegisterCashierId", "CashierRegisterRegisterId");
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.BillProduct", b =>
                {
                    b.HasOne("CashRegister.Data.Entities.Models.Bill", "Bill")
                        .WithMany("BillProducts")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CashRegister.Data.Entities.Models.Product", "Product")
                        .WithMany("BillProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.CashierRegister", b =>
                {
                    b.HasOne("CashRegister.Data.Entities.Models.Cashier", "Cashier")
                        .WithMany("CashierRegisters")
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CashRegister.Data.Entities.Models.Register", "Register")
                        .WithMany("CashierRegisters")
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
