// <auto-generated />
using System;
using CashRegister.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CashRegister.Data.Migrations
{
    [DbContext(typeof(CashRegisterContext))]
    [Migration("20190709075408_AddBillProductsToDb")]
    partial class AddBillProductsToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CashierRegisterCashierId");

                    b.Property<int?>("CashierRegisterRegisterId");

                    b.Property<double>("ExciseDutyAmount");

                    b.Property<Guid>("Guid");

                    b.Property<DateTime>("IssueDate");

                    b.Property<double>("TotalPriceWithTax");

                    b.Property<double>("TotalPriceWithoutTax");

                    b.Property<double>("ValueAddedTaxAmount");

                    b.HasKey("Id");

                    b.HasIndex("CashierRegisterCashierId", "CashierRegisterRegisterId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.BillProduct", b =>
                {
                    b.Property<int>("BillId");

                    b.Property<int>("ProductId");

                    b.Property<double>("PriceAtPurchase");

                    b.Property<int>("TaxAtPurchase");

                    b.HasKey("BillId", "ProductId");

                    b.ToTable("BillProducts");
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Cashier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cashiers");
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.CashierRegister", b =>
                {
                    b.Property<int>("CashierId");

                    b.Property<int>("RegisterId");

                    b.HasKey("CashierId", "RegisterId");

                    b.HasIndex("RegisterId");

                    b.ToTable("CashierRegisters");
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<string>("Barcode");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("Tax");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.Bill", b =>
                {
                    b.HasOne("CashRegister.Data.Entities.Models.CashierRegister", "CashierRegister")
                        .WithMany()
                        .HasForeignKey("CashierRegisterCashierId", "CashierRegisterRegisterId");
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.BillProduct", b =>
                {
                    b.HasOne("CashRegister.Data.Entities.Models.Bill", "Bill")
                        .WithMany("BillProducts")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CashRegister.Data.Entities.Models.Product", "Product")
                        .WithMany("BillProducts")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CashRegister.Data.Entities.Models.CashierRegister", b =>
                {
                    b.HasOne("CashRegister.Data.Entities.Models.Cashier", "Cashier")
                        .WithMany("CashierRegisters")
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CashRegister.Data.Entities.Models.Register", "Register")
                        .WithMany("CashierRegisters")
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
